# Generated by Django 6.0.5 on 2026-05-13 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_user_options_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='images/ads/', verbose_name='Изображение')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('sold', 'Sold')], max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL, verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
            },
        ),
    ]
