# Generated by Django 6.0.5 on 2026-05-15 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_ads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ads',
            new_name='Ad',
        ),
        migrations.AlterModelTable(
            name='ad',
            table='ads',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
