# Generated by Django 6.0.5 on 2026-05-15 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_ads_ad_alter_ad_table_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.RemoveField(
            model_name='ad',
            name='created_at',
        ),
    ]
